

# Site settings
title: 분당우리교회 서현 소년부
description: |
 "file:///C:/Users/%EA%B2%BD%EC%95%A0/Desktop/%EC%97%AC%EB%A6%84%EC%BA%A0%ED%94%84%20%EB%A1%9C%EA%B3%A0/banner.jpg"
owner: 분당우리교회 # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: tifriend0623@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  github: https://github.com/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
